# Generated by Django 4.0.6 on 2022-07-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipeID', models.AutoField(primary_key=True, serialize=False)),
                ('recipeName', models.TextField(max_length=50)),
                ('category', models.TextField(default='', max_length=50)),
                ('ingredient', models.TextField(max_length=400)),
                ('duration', models.DurationField()),
                ('steps', models.TextField(max_length=2000)),
                ('calories', models.FloatField()),
                ('servings', models.FloatField()),
                ('chefName', models.TextField(default='ADMIN', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
