# Generated by Django 4.0.6 on 2022-08-11 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('ingredientID', models.AutoField(primary_key=True, serialize=False)),
                ('ingredientName', models.CharField(max_length=50, unique=True)),
                ('baseCalorie', models.FloatField()),
                ('ingredientImg', models.ImageField(blank=True, default='default/noImage.jpeg', null=True, upload_to='ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('ingredientCategoryID', models.AutoField(primary_key=True, serialize=False)),
                ('ingredientCategoryName', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('categoryID', models.AutoField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utensil',
            fields=[
                ('utensilID', models.AutoField(primary_key=True, serialize=False)),
                ('utensilName', models.CharField(max_length=50, unique=True)),
                ('utensilImg', models.ImageField(blank=True, default='default/noImage.jpeg', null=True, upload_to='utensil')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipeID', models.AutoField(primary_key=True, serialize=False)),
                ('recipeName', models.CharField(max_length=50)),
                ('ingredientAmount', models.JSONField()),
                ('duration', models.DurationField()),
                ('steps', models.TextField(max_length=3000)),
                ('servings', models.FloatField()),
                ('calories', models.FloatField()),
                ('rating', models.FloatField(default=0)),
                ('numRater', models.IntegerField(default=0)),
                ('raters', models.JSONField(default=dict)),
                ('recipeImg', models.ImageField(blank=True, default='default/noImage.jpeg', null=True, upload_to='recipe')),
                ('chefName', models.CharField(default='admin', max_length=50)),
                ('category', models.ManyToManyField(related_name='recipeCategory', to='recipeManager.recipecategory')),
                ('chefID', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ingredient', models.ManyToManyField(related_name='ingredients', to='recipeManager.ingredient')),
                ('utensil', models.ManyToManyField(blank=True, related_name='utensils', to='recipeManager.utensil')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='ingredientCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipeManager.ingredientcategory'),
        ),
    ]
