# Generated by Django 4.0.6 on 2022-08-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredientAmount',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='raters',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
