# Generated by Django 4.0.6 on 2022-08-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeManager', '0003_alter_ingredient_ingredientimg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredientImg',
            field=models.ImageField(blank=True, null=True, upload_to='media/ingredient/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipeImg',
            field=models.ImageField(blank=True, null=True, upload_to='media/recipe/'),
        ),
        migrations.AlterField(
            model_name='utensil',
            name='utensilImg',
            field=models.ImageField(blank=True, null=True, upload_to='media/utensil/'),
        ),
    ]
