# Generated by Django 4.0.6 on 2022-08-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeManager', '0004_alter_ingredient_ingredientimg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utensil',
            name='utensilImg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
