# Generated by Django 4.0.6 on 2022-08-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeManager', '0005_alter_utensil_utensilimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredientImg',
            field=models.ImageField(blank=True, null=True, upload_to='recipeManager/media/ingredient/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipeImg',
            field=models.ImageField(blank=True, null=True, upload_to='recipeManager/media/recipe/'),
        ),
        migrations.AlterField(
            model_name='utensil',
            name='utensilImg',
            field=models.ImageField(blank=True, null=True, upload_to='recipeManager/media/utensil/'),
        ),
    ]
