# Generated by Django 4.0.6 on 2022-08-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeManager', '0008_alter_utensil_utensilimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utensil',
            name='utensilImg',
            field=models.ImageField(blank=True, null=True, upload_to='utensil'),
        ),
    ]
