# Generated by Django 4.0.6 on 2022-08-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeManager', '0009_alter_utensil_utensilimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='numRater',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
