# Generated by Django 4.0.6 on 2022-08-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeManager', '0010_recipe_numrater_alter_recipe_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredientName',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='utensil',
            name='utensilName',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
