# Generated by Django 4.0.6 on 2022-08-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeManager', '0012_alter_ingredient_ingredientimg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientcategory',
            name='ingredientCategoryName',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='recipecategory',
            name='categoryName',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
