# Generated by Django 4.0.6 on 2022-08-07 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeManager', '0013_alter_ingredientcategory_ingredientcategoryname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipeImg',
            field=models.ImageField(blank=True, default='default/noImage.jpeg', null=True, upload_to='recipe'),
        ),
    ]
