# Generated by Django 4.0.6 on 2022-08-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeManager', '0014_alter_recipe_recipeimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='ingredientImg',
            field=models.ImageField(blank=True, default='default/noImage.jpeg', null=True, upload_to='ingredient'),
        ),
    ]
